framework:
    session:
        handler_id: session.handler.memcached

services:
    memcached:
        class: Memcached
        calls:
            - [addServer, ['%env(DATA_MEMCACHED_HOST)%', 11211]]

    session.handler.memcached:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: ['@memcached', { prefix: 'sp_sess_', expiretime: 86400 }]

doctrine:
    orm:
        metadata_cache_driver:
            type: memcached
            host: '%env(DATA_MEMCACHED_HOST)%'
            port: 11211
            instance_class: Memcached
        query_cache_driver:
            type: memcached
            host: '%env(DATA_MEMCACHED_HOST)%'
            port: 11211
            instance_class: Memcached
        result_cache_driver:
            type: memcached
            host: '%env(DATA_MEMCACHED_HOST)%'
            port: 11211
            instance_class: Memcached